### ISSUE TITLE
Updated docs

### ISSUE THREAD

**Issue by willeexl** [applicaster/rn-youtube-android#1]
Hi - can you update the docs for the latest react native?

**Comment by simonvaucher** [comment]
Is there some fundamental change that I need to take care of, or is it just a version number change?

**Comment by willeexl** [comment]
In the Read.me, I don't think the following section applies for RN 0.18+

In the activity that starts React Native, add the package to the ReactInstanceManager builder:
import com.applicaster.RNYouTubePlayer.YoutubePlayerReactPackage;

...

Builder reactManagerBuilder = ReactInstanceManager.builder()
    .setApplication(getApplication())
    .addPackage(new MainReactPackage())
    .addPackage(new YoutubePlayerReactPackage())
    ...
Important: In order to get callbacks from the YouToube player, which runs on a separate activity, add this to the activity that holds the ReactInstanceManager:
private ReactInstanceManager reactInstanceManager; // Initialize it following React Native instructions, above

...

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    reactInstanceManager.onActivityResult(requestCode, resultCode, data);
}

**Comment by simonvaucher** [comment]
It has been tested and working on a real device in version 0.23, so no need to update any docs yet.
https://facebook.github.io/react-native/docs/embedded-app-android.html#content
