### ISSUE TITLE
use of removed method onActivityResult

### ISSUE THREAD

**Issue by kamiranoff** [applicaster/rn-youtube-android#13]
Hi,

YoutubePlayerModule.java overrides a method from ActivityEventListener that has been removed: 
 public void onActivityResult(int requestCode, int resultCode, Intent data).

See : https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35#diff-8b63add5f85adc06c226d8a36c4c2f88

It is still present in BaseActivityEventListener but marked as deprecated.

I tried with react-native 0.37 and higher but could not compile due to :
RNYouTubePlayer/YoutubePlayerModule.java:54: error: method does not override or implement a method from a supertype

**Comment by simonvaucher** [comment]
Hi,

I am using 0.37 for almost 4 months, it shouldn't be a problem, but... 
just to make sure - do you use the package as instructed, i.e., start react package from existing Android app, or the other way around (new project via `react-native` cli etc.).

This package is not intended for apps created with `react-native init (...)`

**Comment by kamiranoff** [comment]
Well it works well if I remove the @override from public void onActivityResult(int requestCode, int resultCode, Intent data).
That is what I had, last month, when I was working on implementing the video. But this time I wanted to avoid coying the souce locally.

I just don't understand how could it compile if YoutubePlayerModule overrides a method that is not defined in the implemented interface.

**Comment by simonvaucher** [comment]
Mmm... the @override is more like a good practice than a compilation error, it is not really required in Java.
I'll look into it, thanks.

**Comment by simonvaucher** [comment]
Hi,
I've removed the offending override in version 2.0.+ ->
https://github.com/applicaster/rn-youtube-android/commit/2db015c6609249a550666c3223714a8b9f0869be
Thanks for your contribution!
