### ISSUE TITLE
react-native 0.29 can't close video(with player "Arrows" button)

### ISSUE THREAD

**Issue by SimchaShats** [applicaster/rn-youtube-android#3]

**Comment by simonvaucher** [comment]
Hi, can you provide a description, please? I can successfully close the video by tapping the physical/virtual "back" button on the device (react-native 0.30).

**Comment by SimchaShats** [comment]
@simonvaucher Hi, android BackButton works me also, but there is on screen of the player in the bottom right corner - button with 2 arrows, that I think should close player, but it only reload video. May be there issue how to initialise  in 0.29 correctly: **private ReactInstanceManager reactInstanceManager;**, sorry, I'm not android developer so may be I missed something?

**Comment by simonvaucher** [comment]
The button with 2 arrows is intended to show in fullscreen, at least in Android 5.0/6.0. It'll be best if you can provide a screenshot, to make sure we are talking on the same button. Thanks! 👍

**Comment by SimchaShats** [comment]
Sorry I can't for now attach image but I will try to explain: I open youtube player, it's open new activity in landscape fullscreen mode (android 6.0.1). And here only one option to exit from fullscreen mode - it's click AndroidBack button (is there any other ways to exit from fullscreen mode?). In the right bottom corner button with 2 arrows (right after YouTube icon), when I click on it, it does nothing, but only reload video. Video always in fullscreen mode and I can't exit from it, but only with Android back button.

**Comment by simonvaucher** [comment]
OK, got it.
Indeed, the new activity is always opened in landscape-fullscreen mode.
I have plans to support in the future also non-fullscreen mode.

Anyhow, the right-bottom button arrows are YouTube's buttons, they cannot be changed, and serve only to enlarge to fullscreen. There is no built-in "back" button as far as I know: 
https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerView

**Comment by SimchaShats** [comment]
Thanks

**Comment by simonvaucher** [comment]
Hi, @SimchaShats - I've removed the "arrows" buttons in version 1.2.8 - since it is a hard-coded fullscreen activity, they are not needed.

It would be best to start moving these styling functions/flags in proper react-native bridges, I am open for PR requests.

Cheers,
Simon
