### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by bogobogo** [applicaster/rn-youtube-android#5]
Your repository looks awesome, would really like to use it, but I am having some problems getting started.

Could you be more clear as to the file in which we should add these lines of code? 

```
import com.applicaster.RNYouTubePlayer.YoutubePlayerReactPackage;
...

Builder reactManagerBuilder = ReactInstanceManager.builder()
    .setApplication(getApplication())
    .addPackage(new MainReactPackage())
    .addPackage(new YoutubePlayerReactPackage())
    ...`

```

_"In the activity that starts React Native, add the package to the ReactInstanceManager builder:"_ 

Which file is that?

It is not clear where they would belong. 

Thanks

**Comment by simonvaucher** [comment]
Please check the quite detailed instructions _for the Android platform_ in React Native's site: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#prepare-your-current-app

React Native can be started from Android activity, e.g., the default MainActivity.

**Comment by cjmling** [comment]
That Builder is not a complete code right ?

**Comment by simonvaucher** [comment]
Sorry, I don't understand the question... @cjmling

**Comment by cjmling** [comment]
@simonvaucher  I mean you told us to copy this exact code into MainActivity.java  right ? Should it be inside onActivityResult ? 

```
Builder reactManagerBuilder = ReactInstanceManager.builder()
.setApplication(getApplication())
    .addPackage(new MainReactPackage())
    .addPackage(new YoutubePlayerReactPackage())
    ...
```

Should there be this which are there in the link u commented above.

```
.setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
```

Sorry I'm newbie.  Thanks

**Comment by simonvaucher** [comment]
This is how the Activity should look like: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#add-native-code
The YoutubePlayerReactPackage is just another package, added using `.addPackage`.
I'm sorry, but a good understanding in Android is required, running react native on Android is not for beginners :)

**Comment by cjmling** [comment]
Yeah i agree may be I should spend some more time learning native Android. 
Till now I had been running react native on android with few other packages though , but may be those were simpler package so easy to integrate.   Thanks anyway :)

**Comment by simonvaucher** [comment]
Yeah, sorry about that. Hopefully I will integrate something like `rnpm` which will link everything via command line, but it is still immature.

**Comment by simonvaucher** [comment]
Update: `rnpm` seems to be getting nowhere, so I'll stick to the tried-and-true instructions for manual integration of the package.
