### ISSUE TITLE
Merge with https://github.com/inProgress-team/react-native-youtube?

### ISSUE THREAD

**Issue by sibelius** [applicaster/rn-youtube-android#6]
do u think it is worth to merge this component into https://github.com/inProgress-team/react-native-youtube?

so we can have a great bridge for both ios and android?

**Comment by simonvaucher** [comment]
Maybe, but this is problematic. The native implementation cannot be more different - webview + javascript bridge in iOS versus YouTube's own 100% native implementation.
Theoretically, if you combine both a same react-native component, you'll get a dozens of flags which are relevant only for iOS, and a dozens of other flags which are relevant only for Android.
For now, I recommend surrounding your player implementation with the very useful `*.ios.js` and  `*.android.js` extension -> see http://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions

**Comment by simonvaucher** [comment]
Update:
I checked inProgress-team's implementation, it is unfortunately still buggy -
mainly due to the issue of other views drawing over the player.
When it'll reach a decent, stable state I'll be happy to deprecate this package.
