### ISSUE TITLE
Uppercase in package name

### ISSUE THREAD

**Issue by kamiranoff** [applicaster/rn-youtube-android#9]
I am not very skillful in Java but it appears that the package name differs by an uppercase T in "RNYouTubePlayer" (or "RNYoutubePlayer").

for example in the manifest :
android:name="com.applicaster.RNYouTubePlayer.YoutubePlayerActivity"
or in any of the java classes: "package com.applicaster.RNYouTubePlayer;"

but in the actual path : "rn-youtube-android/android/src/main/java/com/applicaster/RNYoutubePlayer/"
It is "RnYoutube" with a small "t"

I changed it so I could compile.

**Comment by simonvaucher** [comment]
Nice catch, thanks!
Since inside each .java file the first line has always the same package name, `package com.applicaster.RNYouTubePlayer;` it compiles in our machines fine, disregarding the folder name. Actually, you can have a totally different folder name and it will still work due to the package declaration inside the file.
But of course, that's a typo, I'll notify here when completing the fix.

**Comment by simonvaucher** [comment]
Haha, I encountered this funny behavior in past - 
When renaming directories, git ignores completely upper/lower cases, so no change is detected when I rename the directory. I'll have to find a way around that.

**Comment by simonvaucher** [comment]
OK, the plot THICKENS - directories cases are ignored in osx and windows. If you are using some normal linux, it should fail to compile, as you mentioned.

**Comment by kamiranoff** [comment]
Maybe it was not the reason i could not compile at first then ;) 
I think my imports were messed up. Could be the ide... (On mac with android studio)
Anyway glad I could help.

I use your library for an app i am building at work. Works Great :)
 
something like that maybe  git mv --force myfile MyFile

**Comment by simonvaucher** [comment]
Fixed: https://github.com/applicaster/rn-youtube-android/pull/10
Thank you very much, @kamiranoff !

I assume my IDE was configured differently...
